[package]
name = "account-sdk"
edition.workspace = true
version.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["lib"]

[dependencies]
anyhow.workspace = true
async-trait.workspace = true
base64.workspace = true
cainome.workspace = true
cairo-lang-starknet.workspace = true
coset.workspace = true
ecdsa.workspace = true
futures.workspace = true
lazy_static.workspace = true
p256.workspace = true
primitive-types.workspace = true
rand_core.workspace = true
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
starknet.workspace = true
starknet-crypto.workspace = true
thiserror.workspace = true
toml.workspace = true
u256-literal.workspace = true
url.workspace = true
wasm-bindgen-futures.workspace = true
wasm-bindgen.workspace = true
wasm-webauthn.workspace = true
web-sys = "0.3.69"

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
tokio.workspace = true

[target.'cfg(target_arch = "wasm32")'.dependencies]
wasm-bindgen-test = "0.3.34"
js-sys = "0.3.69"
